server:
  port: 8091


# Database Connection
spring:
  datasource:
    url: jdbc:postgresql://alizon.ch33ag9rchic.us-east-1.rds.amazonaws.com:5432/compras
    username: alizon
    password: Alizon2020
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  file:
    path: C:/spring-boot-app.log